version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.1.0
jobs:
  install:
    docker:
      - image: circleci/node:12
    resource_class: large

    working_directory: ~/react-spectrum
    steps:
      - checkout
      - restore_cache:
          keys:
            rsp-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            rsp-yarn-{{ .Branch }}-
            rsp-yarn-

      - run:
          name: Write npmrc
          command: |
            if [ $NPM_PASSWORD ]; then
              cp .circleci/.npmrc .npmrc
            fi

      - run:
          name: build
          command: |
            yarn --pure-lockfile --cache-folder ~/.cache/yarn
            rm -rf .git/
            mkdir dist

      - save_cache:
         paths:
           - ~/.cache/yarn
         key: rsp-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - save_cache:
          paths:
            - ~/react-spectrum
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

  install-17:
    docker:
      - image: circleci/node:12
    resource_class: large

    working_directory: ~/react-spectrum
    steps:
      - checkout
      - restore_cache:
          keys:
            rsp-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            rsp-yarn-{{ .Branch }}-
            rsp-yarn-

      - run:
          name: build
          command: |
            yarn install --pure-lockfile --cache-folder ~/.cache/yarn && yarn install-17 --cache-folder ~/.cache/yarn
            rm -rf .git/
            mkdir dist

      - save_cache:
          paths:
            - ~/react-spectrum
          key: react-spectrum-17-{{ .Environment.CIRCLE_SHA1 }}

  test:
    docker:
      - image: circleci/node:12

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: test
          command: yarn ci-test

  test-17:
    docker:
      - image: circleci/node:12

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-17-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: test
          command: yarn ci-test-17

  lint:
    docker:
      - image: circleci/node:12

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: lint
          command: yarn lint

  storybook:
    docker:
      - image: circleci/node:12
    resource_class: large

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build storybook
          command: make storybook

      - persist_to_workspace:
          root: dist
          paths:
            - 'dist/storybook'

  storybook-17:
    docker:
      - image: circleci/node:12
    resource_class: large

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-17-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build storybook-17
          command: make storybook-17

      - persist_to_workspace:
          root: dist
          paths:
            - 'dist/storybook-17'

  docs:
    docker:
      - image: circleci/node:12
    resource_class: xlarge

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build docs
          command: make website

      - persist_to_workspace:
          root: dist
          paths:
            - 'dist/docs'

  docs-production:
    docker:
      - image: circleci/node:12
    resource_class: xlarge

    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build docs
          command: make website-production

      - persist_to_workspace:
          root: dist
          paths:
            - 'dist/docs'

  deploy:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: |
            if [ $AZURE_STORAGE_SAS_TOKEN ]; then
              az storage blob upload-batch -d reactspectrum -s /tmp/dist --account-name reactspectrum
            fi

  deploy-production:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: az storage blob upload-batch -d "\$web" -s /tmp/dist/production/docs --account-name reactspectrum

  comment:
    docker:
      - image: circleci/node:12
    working_directory: ~/react-spectrum
    steps:
      - checkout
      - restore_cache:
          keys:
            rsp-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            rsp-yarn-{{ .Branch }}-
            rsp-yarn-

      - run:
          name: install
          command: |
            SKIP_BUILDING_ICONS="true" && yarn install --pure-lockfile --cache-folder ~/.cache/yarn

      - run:
          name: comment on pr
          command: |
            if [ $GITHUB_TOKEN ]; then
              node .circleci/comment.js
            fi

  publish-nightly:
    docker:
      - image: circleci/node:12
    resource_class: xlarge
    working_directory: ~/react-spectrum
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Authenticate with npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            git update-index --skip-worktree .npmrc
      - run:
          name: Publish
          command: make publish-nightly

workflows:
  version: 2
  commit:
    jobs:
      - install
      - install-17
      - test:
          requires:
            - install
      - test-17:
          requires:
            - install-17
      - lint:
          requires:
            - install
      - storybook:
          requires:
            - install
      - storybook-17:
          requires:
            - install-17
      - docs:
          requires:
            - install
      - docs-production:
          filters:
            branches:
              only: main
          requires:
            - install
      - deploy:
          requires:
            - lint
            - test
            - test-17
            - storybook
            - storybook-17
            - docs
      - deploy-production:
          filters:
            branches:
              only: main
          requires:
            - docs-production
      - comment:
          requires:
            - deploy

  nightly:
    triggers:
      - schedule:
          cron: "0 9 * * *" # 02:00 PDT
          filters:
            branches:
              only:
                - main
    jobs:
      - install
      - publish-nightly
