version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.1.0
jobs:
  build-image:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/react-spectrum-v3
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Write npmrc
          command: |
            cp .circleci/.npmrc .npmrc

      - run:
          name: yarn install
          command: |
            make clean_node_modules
            make install_no_postinstall

      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ checksum "yarn.lock" }}

      - run:
          name: build
          command: |
            make clean
            make -B

      - save_cache:
          paths:
            - ~/react-spectrum-v3
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}

  build:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/react-spectrum-v3
    steps:
      - restore_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build
          command: |
            make clean
            make -B

  test:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/react-spectrum-v3
    steps:
      - restore_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: test
          command: make ci-test

  storybook:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/react-spectrum-v3
    steps:
      - restore_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build storybook
          command: make storybook

      - save_cache:
          key: v3-storybook-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/react-spectrum-v3/dist/*/storybook/
  docs:
    docker:
      - image: circleci/node:12.10

    working_directory: ~/react-spectrum-v3
    steps:
      - restore_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build docs
          command: make website

      - save_cache:
          key: v3-docs-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/react-spectrum-v3/dist/*/docs/

  deploy:
    executor: azure-cli/azure-docker
    steps:
      - restore_cache:
          key: v3-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v3-storybook-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v3-docs-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: az storage blob upload-batch -d reactspectrum -s /tmp/dist --account-name reactspectrum

  comment:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/react-spectrum-v3
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}

      - run:
          name: comment on pr
          command: node .circleci/comment.js

workflows:
  version: 2
  test:
    jobs:
      - build-image
      - test:
          requires:
            - build-image
      - storybook:
          requires:
            - build-image
      - docs:
          requires:
            - build-image
      - deploy:
          requires:
            - test
            - storybook
            - docs
      - comment:
          requires:
            - deploy
